name: deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout respositpry
      id: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0



